In [1]:
import os
import warnings
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
#os.environ['CUDA_LAUNCH_BLOCKING'] = str(1)
#os.environ["TORCH_USE_CUDA_DSA"]= str(0)
warnings.filterwarnings('ignore') 


In [2]:
import copy
import torch
import torch.nn as nn
from torch.nn import functional as F
from torch.utils.data import Dataset
import torch.optim as optim
from torch.autograd import Variable
from tqdm import tqdm
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
import math
from collections import OrderedDict
import random
from torchsummary import summary
from torchvision import transforms
from torch.utils.data import Dataset
import sys
import torch
import numpy as np
from tqdm import trange
from torch.utils.data import DataLoader
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import mne
from sklearn.preprocessing import StandardScaler
import logging
from torch.nn.utils.rnn import pack_sequence, pad_packed_sequence
import statistics
import torch.optim.lr_scheduler as lr_scheduler
from scipy.special import softmax
from sklearn.model_selection import StratifiedKFold

In [3]:
logging.getLogger('mne').setLevel(logging.WARNING)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
import import_ipynb
#from Model import net
from Dataloader2 import EEGDataset

importing Jupyter notebook from Dataloader2.ipynb


In [4]:
def Accuracy(y_pred, y, train_count):
    max_values, _ = torch.max(y_pred, dim=1, keepdim=True)
    mask = y_pred == max_values
    y_pred = mask.int()
    correct_num = torch.sum(torch.all(torch.eq(y, y_pred), dim=1)).item()
    accuracy = correct_num / train_count
    return accuracy * 100

In [5]:
def test(model, test_path, test_class, verbose=True):
    

    x_test = mne.read_epochs(test_path, preload=False).get_data(picks='eeg');
    normals = []
    scaler = StandardScaler()
    for idx in range(len(x_test)):
        normals.append(scaler.fit_transform(x_test[idx]))
    normals = torch.tensor(normals).cuda().float()
    result = torch.argmax(model(normals), axis=1)
    unique_elements, counts = torch.unique(result, return_counts=True)

    votes = np.zeros([4])
    for i in range(len(unique_elements)):
        votes[unique_elements[i]] = counts[i]


    if(verbose):
        print(f"Test Accuracy: {(votes[test_class] / result.shape[0]) * 100}")
    return votes


In [6]:
class net(nn.Module):
    def __init__(self, T, C, input_size, hidden_size, num_layers, spatial_num, dropout, pool):
        super(net, self).__init__()
        
        self.T = T
        self.C = C
        self.spatial_num = spatial_num
        self.dropout = dropout
        self.pool = pool

        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers

        self.cell_count = self.T // self.input_size

        self.fcn_in = (spatial_num * self.hidden_size)

        self._lstm = nn.LSTM(self.input_size, self.hidden_size, self.num_layers, batch_first=True)

        self.lstm = nn.ModuleList([self._lstm for i in range(self.C)])

        self.cnn_block = nn.Sequential(nn.Conv2d(1, self.spatial_num, (self.C, 1)),
                                       nn.BatchNorm2d(self.spatial_num),
                                       nn.ELU(),



                                       nn.Dropout(self.dropout))

        
        self.fcn = nn.Sequential(nn.Linear(self.fcn_in, 128), 
                                 nn.ReLU(),
                                 nn.Linear(128, 16),
                                 nn.Dropout(self.dropout),
                                 nn.ReLU(),
                                 nn.Linear(16, 4))

        #self.fcn = nn.Linear(self.fcn_in, 4)
        self.results = nn.Softmax(dim=1)
    def forward(self, x):
        x = x.reshape(-1, 1, 19, 3000)
        self.N = x.shape[0]
        x = x.reshape(self.N, self.C, self.cell_count, self.input_size)
        _x = None

        for index, cell in enumerate(self.lstm):
            cell_out, _ = cell(x[:, index, :, :], None)
            last_layer_out = cell_out[:, -1, :]
            
            last_layer_out = last_layer_out.unsqueeze(0)
            if _x is None:
                _x = last_layer_out
            else:
                _x = torch.cat((_x, last_layer_out), dim=0)
            

        x = _x.permute(1, 0, 2).unsqueeze(1)

        x = self.cnn_block(x)


        x = x.reshape(self.N, -1)

        x = self.fcn(x)
        x = self.results(x)

        return x

In [7]:
class CNN_LSTM(nn.Module):
    def __init__(self, num_classes, hidden_size):
        super(CNN_LSTM, self).__init__()
        
        self.num_classes = num_classes
        self.hidden_size =hidden_size
        self.dropout = 0.5
        # CNN layers
        self.conv1 = nn.Conv1d(19, 32, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv1d(32, 64, kernel_size=3, stride=1, padding=1)
        self.conv3 = nn.Conv1d(64, 128, kernel_size=3, stride=1, padding=1)
        self.pool = nn.MaxPool1d(2)
        
        # LSTM layers
        self.lstm = nn.LSTM(3000, self.hidden_size, num_layers=1, batch_first=True)
        
        # Fully connected layer
        self.fc = nn.Sequential(nn.Linear(self.hidden_size * 128, 128), 
                                 nn.ReLU(),
                                 nn.Linear(128, 16),
                                 nn.Dropout(self.dropout),
                                 nn.ReLU(),
                                 nn.Linear(16, self.num_classes))
        

        self.results = nn.Softmax(dim=1)
        
        
    def forward(self, x):
        x = x.reshape(-1, 19, 3000)
        self.N = x.shape[0]
        # Apply CNN
        x = F.relu(self.conv1(x))
        #x = self.pool(x)
        
        
        x = F.relu(self.conv2(x))
        #x = self.pool(x)
        
        x = F.relu(self.conv3(x))
        # Reshape for LSTM
        
        #x = x.transpose(1, 2)
        xx = x
        # Apply LSTM
        h_n, (__, _) = self.lstm(x)

        x = h_n[:, :, :]
        
        # Apply fully connected layer
        x = x.reshape(self.N, -1)
        x = self.fc(x)
        x = self.results(x)
        """
        """
        return x
    
model = CNN_LSTM(num_classes=4, hidden_size=100).cuda()
model(torch.rand(7, 19, 3000).cuda()).shape

torch.Size([7, 4])

In [8]:
MNE_Data = EEGDataset(root_dir=r"C:\Users\admin\Desktop\MNE_Data")
labels = MNE_Data.labels
#MNE_Data = EEGDataset(root_dir=r"D:\TEST MNE")
test_path = r"C:\Users\admin\Desktop\TEST\amirifateme.fif"
test_class = 0

In [9]:
train_dataloader = DataLoader(MNE_Data, batch_size=1, shuffle=True)

In [10]:
model = net(T = 3000, C = 19, input_size = 3000, hidden_size = 100, num_layers=1, spatial_num= 300, dropout=0.5, pool=1).to(device)
#model = CNN_LSTM(num_classes=4, hidden_size=100).cuda()
num_params = sum(p.numel() for p in model.parameters())
print("Number of parameters:", num_params)

Number of parameters: 5089660


In [11]:
criterion = nn.CrossEntropyLoss(weight = torch.Tensor([5.3125, 1.8333, 3.5417, 6.6667]).cuda())

optimizer = optim.Adam(model.parameters(), lr=0.001)
#optimizer = optim.Adagrad(model.parameters(), lr=0.001)


scheduler = lr_scheduler.ExponentialLR(optimizer, gamma=0.1)
epochs = 40
kf = StratifiedKFold(n_splits=5)
model_list = []

In [12]:
for train_indices, val_indices in kf.split(MNE_Data, labels):
    train_dataset = torch.utils.data.Subset(MNE_Data, train_indices)
    val_dataset = torch.utils.data.Subset(MNE_Data, val_indices)

    train_dataloader = torch.utils.data.DataLoader(train_dataset, batch_size=1, shuffle=True)
    val_dataloader = torch.utils.data.DataLoader(val_dataset, batch_size=1, shuffle=False)

    test_log = []
    log = []


    model = net(T = 3000, C = 19, input_size = 3000, hidden_size = 100, num_layers=1, spatial_num= 300, dropout=0.5, pool=1).to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    for epoch in trange(epochs):
        
        model.train()   
        for index, data in enumerate(train_dataloader):
                
                x, y = data
                y = y.to(torch.float64)
                x = x.reshape(-1, 1, 19, 3000).float()
                x = x[torch.randperm(x.shape[0])]
                y = F.one_hot(torch.tensor(torch.tensor([y.item()]).to(torch.int64)), num_classes=4).expand(x.shape[0], -1).float()
                
                train_count = x.shape[0]
                x, y = x.to(device), y.to(device)
                y_pred = model(x)
                loss = criterion(y_pred, y)
                
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
                #scheduler.step()
                torch.cuda.empty_cache()

    
        model.eval()
        val_loss = 0
        val_log = []
        with torch.no_grad():
            for batch_idx, (data, target) in enumerate(val_dataloader):
                        data = data.reshape(-1, 1, 19, 3000).float().cuda()
                        target = F.one_hot(torch.tensor(torch.tensor([target.item()]).to(torch.int64)), num_classes=4).expand(data.shape[0], -1).float().cuda()
                        

                        output = model(data)

                        

                        loss = criterion(output, target)
                        
                        val_loss += loss.item()

                        val_log.append(Accuracy(output, target, target.shape[0]))

        print(model(x.cuda())[-1])     
        print(y[-1])           
        print('Epoch: {}, Validation Loss: {:.4f}, Validation Accuracy: {:.2f}%'.format(
                    epoch, val_loss / len(val_dataloader), statistics.mean(val_log)))

    model_list.append(model)
        


    


  2%|▎         | 1/40 [00:47<30:38, 47.14s/it]

tensor([5.4358e-06, 9.9991e-01, 8.0506e-05, 8.0854e-06], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 0, Validation Loss: 5.9834, Validation Accuracy: 35.29%


  5%|▌         | 2/40 [01:34<29:46, 47.00s/it]

tensor([0.2712, 0.2465, 0.2343, 0.2480], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 1, Validation Loss: 5.2731, Validation Accuracy: 17.65%


  8%|▊         | 3/40 [02:20<28:53, 46.86s/it]

tensor([0.2704, 0.2428, 0.2359, 0.2509], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 2, Validation Loss: 5.2711, Validation Accuracy: 17.67%


 10%|█         | 4/40 [03:08<28:13, 47.04s/it]

tensor([0.2702, 0.2393, 0.2362, 0.2543], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 3, Validation Loss: 5.2694, Validation Accuracy: 17.72%


 12%|█▎        | 5/40 [03:55<27:25, 47.01s/it]

tensor([0.2706, 0.2357, 0.2380, 0.2557], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 4, Validation Loss: 5.2678, Validation Accuracy: 17.65%


 15%|█▌        | 6/40 [04:43<26:59, 47.64s/it]

tensor([0.2706, 0.2326, 0.2382, 0.2587], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 5, Validation Loss: 5.2661, Validation Accuracy: 17.89%


 18%|█▊        | 7/40 [05:32<26:26, 48.09s/it]

tensor([0.2711, 0.2300, 0.2396, 0.2593], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 6, Validation Loss: 5.2650, Validation Accuracy: 17.70%


 20%|██        | 8/40 [06:20<25:35, 48.00s/it]

tensor([0.1337, 0.2337, 0.3730, 0.2595], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 7, Validation Loss: 5.2638, Validation Accuracy: 21.79%


 22%|██▎       | 9/40 [07:07<24:39, 47.72s/it]

tensor([0.2718, 0.2234, 0.2401, 0.2646], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 8, Validation Loss: 5.2594, Validation Accuracy: 18.00%


 25%|██▌       | 10/40 [07:54<23:41, 47.37s/it]

tensor([0.2711, 0.2208, 0.2410, 0.2671], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 9, Validation Loss: 5.2549, Validation Accuracy: 18.35%


 28%|██▊       | 11/40 [08:42<22:56, 47.48s/it]

tensor([0.2706, 0.2179, 0.2423, 0.2692], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 10, Validation Loss: 5.2462, Validation Accuracy: 19.98%


 30%|███       | 12/40 [09:30<22:18, 47.79s/it]

tensor([0.2725, 0.2141, 0.2412, 0.2722], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 11, Validation Loss: 5.2502, Validation Accuracy: 20.63%


 32%|███▎      | 13/40 [10:19<21:38, 48.07s/it]

tensor([0.2730, 0.2111, 0.2409, 0.2750], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 12, Validation Loss: 5.2694, Validation Accuracy: 22.73%


 35%|███▌      | 14/40 [11:06<20:44, 47.86s/it]

tensor([3.8612e-07, 3.9155e-06, 1.0000e+00, 4.5043e-11], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 13, Validation Loss: 5.4286, Validation Accuracy: 25.08%


 38%|███▊      | 15/40 [11:54<19:53, 47.74s/it]

tensor([3.0991e-12, 1.0000e+00, 7.9214e-13, 2.4696e-10], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 14, Validation Loss: 5.2880, Validation Accuracy: 20.80%


 40%|████      | 16/40 [12:41<19:01, 47.57s/it]

tensor([0.2757, 0.2037, 0.2373, 0.2833], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 15, Validation Loss: 5.2917, Validation Accuracy: 21.37%


 42%|████▎     | 17/40 [13:28<18:09, 47.38s/it]

tensor([0.2762, 0.2011, 0.2356, 0.2871], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 16, Validation Loss: 5.3210, Validation Accuracy: 21.76%


 45%|████▌     | 18/40 [14:15<17:23, 47.45s/it]

tensor([1.6460e-23, 3.0534e-18, 1.0000e+00, 7.0177e-29], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 17, Validation Loss: 5.3154, Validation Accuracy: 22.48%


 48%|████▊     | 19/40 [15:03<16:35, 47.39s/it]

tensor([3.3333e-15, 7.2799e-13, 1.0000e+00, 4.1452e-20], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 18, Validation Loss: 5.2918, Validation Accuracy: 22.47%


 50%|█████     | 20/40 [15:50<15:49, 47.46s/it]

tensor([0.2789, 0.1935, 0.2310, 0.2966], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 19, Validation Loss: 5.2953, Validation Accuracy: 21.19%


 52%|█████▎    | 21/40 [16:37<14:56, 47.21s/it]

tensor([1.5051e-18, 4.5545e-12, 1.0000e+00, 1.8796e-21], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 20, Validation Loss: 5.3049, Validation Accuracy: 21.41%


 55%|█████▌    | 22/40 [17:25<14:15, 47.56s/it]

tensor([6.4021e-24, 4.6495e-21, 1.0000e+00, 2.3772e-31], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 21, Validation Loss: 5.2957, Validation Accuracy: 21.60%


 57%|█████▊    | 23/40 [18:13<13:31, 47.75s/it]

tensor([0.2842, 0.1861, 0.2239, 0.3058], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 22, Validation Loss: 5.3201, Validation Accuracy: 21.62%


 60%|██████    | 24/40 [19:01<12:41, 47.62s/it]

tensor([0.2851, 0.1834, 0.2220, 0.3095], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 23, Validation Loss: 5.3206, Validation Accuracy: 22.20%


 62%|██████▎   | 25/40 [19:48<11:51, 47.46s/it]

tensor([0.2872, 0.1809, 0.2183, 0.3136], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 24, Validation Loss: 5.3565, Validation Accuracy: 21.93%


 65%|██████▌   | 26/40 [20:34<10:58, 47.04s/it]

tensor([0.2883, 0.1785, 0.2171, 0.3160], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 25, Validation Loss: 5.3227, Validation Accuracy: 21.83%


 68%|██████▊   | 27/40 [21:20<10:09, 46.90s/it]

tensor([0.2892, 0.1760, 0.2144, 0.3204], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 26, Validation Loss: 5.3173, Validation Accuracy: 21.64%


 70%|███████   | 28/40 [22:07<09:20, 46.74s/it]

tensor([0.2908, 0.1737, 0.2119, 0.3236], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 27, Validation Loss: 5.3172, Validation Accuracy: 21.28%


 72%|███████▎  | 29/40 [22:53<08:32, 46.55s/it]

tensor([0.2915, 0.1709, 0.2095, 0.3281], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 28, Validation Loss: 5.3076, Validation Accuracy: 21.85%


 75%|███████▌  | 30/40 [23:39<07:44, 46.45s/it]

tensor([0.2923, 0.1691, 0.2073, 0.3313], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 29, Validation Loss: 5.3495, Validation Accuracy: 21.57%


 78%|███████▊  | 31/40 [24:25<06:56, 46.30s/it]

tensor([0.0954, 0.4522, 0.0683, 0.3841], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 30, Validation Loss: 5.3579, Validation Accuracy: 21.78%


 80%|████████  | 32/40 [25:11<06:10, 46.25s/it]

tensor([3.8368e-12, 7.0015e-09, 1.0000e+00, 1.1034e-12], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 31, Validation Loss: 5.3699, Validation Accuracy: 22.55%


 82%|████████▎ | 33/40 [25:57<05:22, 46.03s/it]

tensor([0.2967, 0.1617, 0.1995, 0.3420], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 32, Validation Loss: 5.3415, Validation Accuracy: 22.35%


 85%|████████▌ | 34/40 [26:43<04:35, 45.94s/it]

tensor([3.5369e-21, 1.0000e+00, 7.4109e-22, 1.7650e-10], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 33, Validation Loss: 5.3558, Validation Accuracy: 22.57%


 88%|████████▊ | 35/40 [27:29<03:49, 45.97s/it]

tensor([0.2987, 0.1575, 0.1954, 0.3485], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 34, Validation Loss: 5.3107, Validation Accuracy: 22.32%


 90%|█████████ | 36/40 [28:14<03:02, 45.74s/it]

tensor([0.3003, 0.1547, 0.1919, 0.3531], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 35, Validation Loss: 5.3566, Validation Accuracy: 22.31%


 92%|█████████▎| 37/40 [28:57<02:14, 44.97s/it]

tensor([0.3009, 0.1528, 0.1896, 0.3567], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 36, Validation Loss: 5.3119, Validation Accuracy: 22.27%


 95%|█████████▌| 38/40 [29:40<01:28, 44.45s/it]

tensor([2.6608e-20, 1.0000e+00, 3.0673e-20, 1.6013e-08], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 37, Validation Loss: 5.3162, Validation Accuracy: 22.25%


 98%|█████████▊| 39/40 [30:23<00:44, 44.01s/it]

tensor([0.3033, 0.1478, 0.1844, 0.3646], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 38, Validation Loss: 5.3995, Validation Accuracy: 22.53%


100%|██████████| 40/40 [31:06<00:00, 46.67s/it]


tensor([0.3048, 0.1459, 0.1823, 0.3669], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 39, Validation Loss: 5.3580, Validation Accuracy: 21.99%


  2%|▎         | 1/40 [00:43<28:00, 43.10s/it]

tensor([7.7220e-14, 1.6491e-10, 1.0000e+00, 2.1990e-08], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 0, Validation Loss: 5.5890, Validation Accuracy: 29.41%


  5%|▌         | 2/40 [01:25<27:11, 42.94s/it]

tensor([4.8167e-14, 3.1870e-11, 1.0000e+00, 5.0703e-08], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 1, Validation Loss: 5.5890, Validation Accuracy: 29.41%


  8%|▊         | 3/40 [02:08<26:29, 42.95s/it]

tensor([1.7281e-14, 1.4075e-11, 1.0000e+00, 2.8070e-08], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 2, Validation Loss: 5.5890, Validation Accuracy: 29.41%


 10%|█         | 4/40 [02:52<25:49, 43.04s/it]

tensor([1.8534e-14, 1.5014e-11, 1.0000e+00, 3.4592e-08], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 3, Validation Loss: 5.5890, Validation Accuracy: 29.41%


 12%|█▎        | 5/40 [03:34<25:04, 43.00s/it]

tensor([4.7468e-09, 2.4880e-07, 9.9999e-01, 1.1244e-05], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 4, Validation Loss: 5.5890, Validation Accuracy: 29.41%


 15%|█▌        | 6/40 [04:17<24:19, 42.94s/it]

tensor([8.3797e-05, 4.2606e-04, 9.9902e-01, 4.7459e-04], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 5, Validation Loss: 5.5874, Validation Accuracy: 29.41%


 18%|█▊        | 7/40 [05:00<23:38, 42.98s/it]

tensor([4.7602e-05, 2.9964e-04, 9.9933e-01, 3.2725e-04], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 6, Validation Loss: 5.5874, Validation Accuracy: 29.41%


 20%|██        | 8/40 [05:44<23:02, 43.21s/it]

tensor([0.0014, 0.0044, 0.9889, 0.0053], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 7, Validation Loss: 5.5837, Validation Accuracy: 29.41%


 22%|██▎       | 9/40 [06:27<22:15, 43.09s/it]

tensor([0.0684, 0.0912, 0.7009, 0.1396], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 8, Validation Loss: 5.2932, Validation Accuracy: 28.88%


 25%|██▌       | 10/40 [07:11<21:37, 43.27s/it]

tensor([0.2704, 0.1992, 0.2700, 0.2603], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 9, Validation Loss: 5.2399, Validation Accuracy: 18.80%


 28%|██▊       | 11/40 [07:54<20:53, 43.22s/it]

tensor([0.2706, 0.1955, 0.2721, 0.2618], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 10, Validation Loss: 5.2592, Validation Accuracy: 22.70%


 30%|███       | 12/40 [08:37<20:08, 43.15s/it]

tensor([0.3209, 0.1850, 0.2374, 0.2567], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 11, Validation Loss: 5.2851, Validation Accuracy: 21.99%


 32%|███▎      | 13/40 [09:20<19:30, 43.34s/it]

tensor([1.3642e-27, 1.4620e-27, 3.1327e-14, 1.0000e+00], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 12, Validation Loss: 5.3560, Validation Accuracy: 19.29%


 35%|███▌      | 14/40 [10:04<18:48, 43.42s/it]

tensor([0.2883, 0.1866, 0.2673, 0.2579], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 13, Validation Loss: 5.3006, Validation Accuracy: 22.57%


 38%|███▊      | 15/40 [10:48<18:12, 43.69s/it]

tensor([0.2685, 0.1898, 0.2818, 0.2600], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 14, Validation Loss: 5.2907, Validation Accuracy: 23.40%


 40%|████      | 16/40 [11:33<17:38, 44.08s/it]

tensor([0.0134, 0.0193, 0.2758, 0.6915], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 15, Validation Loss: 5.3069, Validation Accuracy: 25.24%


 42%|████▎     | 17/40 [12:18<16:59, 44.31s/it]

tensor([0.2674, 0.1878, 0.2856, 0.2591], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 16, Validation Loss: 5.3380, Validation Accuracy: 24.64%


 45%|████▌     | 18/40 [13:04<16:25, 44.80s/it]

tensor([9.9997e-01, 2.1230e-06, 2.1117e-06, 2.1856e-05], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 17, Validation Loss: 5.3084, Validation Accuracy: 24.51%


 48%|████▊     | 19/40 [13:49<15:42, 44.87s/it]

tensor([2.6162e-07, 6.3458e-08, 6.8383e-04, 9.9932e-01], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 18, Validation Loss: 5.3027, Validation Accuracy: 26.91%


 50%|█████     | 20/40 [14:34<14:59, 44.97s/it]

tensor([0.0826, 0.2324, 0.5134, 0.1715], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 19, Validation Loss: 5.3002, Validation Accuracy: 26.53%


 52%|█████▎    | 21/40 [15:20<14:19, 45.24s/it]

tensor([1.8724e-09, 8.2973e-09, 1.2201e-04, 9.9988e-01], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 20, Validation Loss: 5.2897, Validation Accuracy: 27.40%


 55%|█████▌    | 22/40 [16:06<13:34, 45.25s/it]

tensor([1.4766e-09, 1.5120e-04, 9.9978e-01, 7.3016e-05], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 21, Validation Loss: 5.3116, Validation Accuracy: 25.16%


 57%|█████▊    | 23/40 [16:50<12:45, 45.01s/it]

tensor([1.3889e-14, 2.4297e-06, 1.0000e+00, 5.0298e-08], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 22, Validation Loss: 5.3109, Validation Accuracy: 26.29%


 60%|██████    | 24/40 [17:34<11:56, 44.77s/it]

tensor([3.4930e-10, 1.0735e-04, 9.9985e-01, 4.2502e-05], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 23, Validation Loss: 5.3102, Validation Accuracy: 26.88%


 62%|██████▎   | 25/40 [18:18<11:07, 44.51s/it]

tensor([9.9999e-01, 3.8403e-06, 4.7991e-07, 3.5503e-06], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 24, Validation Loss: 5.3305, Validation Accuracy: 25.77%


 65%|██████▌   | 26/40 [19:02<10:20, 44.30s/it]

tensor([0.2786, 0.1893, 0.2855, 0.2467], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 25, Validation Loss: 5.3214, Validation Accuracy: 25.72%


 68%|██████▊   | 27/40 [19:47<09:37, 44.42s/it]

tensor([1.2825e-10, 2.1348e-04, 9.9748e-01, 2.3052e-03], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 26, Validation Loss: 5.3094, Validation Accuracy: 27.23%


 70%|███████   | 28/40 [20:32<08:57, 44.83s/it]

tensor([1.2439e-16, 2.2528e-14, 1.9603e-09, 1.0000e+00], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 27, Validation Loss: 5.3038, Validation Accuracy: 26.39%


 72%|███████▎  | 29/40 [21:17<08:11, 44.64s/it]

tensor([8.5324e-18, 3.2502e-06, 1.0000e+00, 2.4871e-10], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 1., 0.], device='cuda:0')
Epoch: 28, Validation Loss: 5.3129, Validation Accuracy: 27.48%


 75%|███████▌  | 30/40 [22:02<07:29, 44.91s/it]

tensor([5.3003e-23, 3.6806e-18, 8.6987e-13, 1.0000e+00], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 1., 0., 0.], device='cuda:0')
Epoch: 29, Validation Loss: 5.3107, Validation Accuracy: 26.77%


 78%|███████▊  | 31/40 [23:16<08:03, 53.70s/it]

tensor([1.0074e-24, 1.0541e-17, 1.7711e-13, 1.0000e+00], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 30, Validation Loss: 5.3105, Validation Accuracy: 27.09%


 80%|████████  | 32/40 [24:33<08:05, 60.73s/it]

tensor([0.6245, 0.1306, 0.1194, 0.1254], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([0., 0., 0., 1.], device='cuda:0')
Epoch: 31, Validation Loss: 5.2957, Validation Accuracy: 27.49%


 82%|████████▎ | 33/40 [25:51<07:41, 65.87s/it]

tensor([1.0000e+00, 6.1547e-08, 1.1206e-10, 1.2892e-10], device='cuda:0',
       grad_fn=<SelectBackward0>)
tensor([1., 0., 0., 0.], device='cuda:0')
Epoch: 32, Validation Loss: 5.3362, Validation Accuracy: 26.25%


In [ ]:
state_dict = model.state_dict()
avg_state_dict = state_dict
for key in state_dict:
    avg_state_dict[key] += state_dict[key]
    print(state_dict[key].shape)
    print('lol')

torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size([400, 3000])
lol
torch.Size([400, 100])
lol
torch.Size([400])
lol
torch.Size([400])
lol
torch.Size

In [ ]:
test(test_path=r"C:\Users\admin\Desktop\TEST\FOCAL\aliabdollahi.fif", model=model, test_class= 3)

FileNotFoundError: File does not exist: "C:\Users\admin\Desktop\TEST\FOCAL\aliabdollahi.fif"

In [ ]:
file_path = 'D:\model weights\model_weights.pth'
torch.save(model.state_dict(), file_path)
model.load_state_dict(torch.load(file_path))

<All keys matched successfully>